### PR TITLE
Made changes to start_clearinghouse_components.sh

### PR DESCRIPTION
**Pull request by asm582**
when i used CTRL+C to terminate shell script but ubuntu reported segfault. Changed the kill command and i think the script works now without segfault.

### CODE REVIEW

**Comment by JustinCappos** [comment]
Why does this fix the problem?  I don't understand what your change does differently than the original code...

**Comment by asm582** [comment]
Currently in kill command implementation we give a negative process ID which tries to kill all the child processes, implemented via trap and passed to shutdown() call in the shell script. Ubuntu keeps calling shutdown() and after a while the script abruptly terminates with seg fault. pkill -P gives all the process ID's in a group and it kills all the required spawned processes without any recursive calls.

**Comment by lukpueh** [comment]
As mentioned above `kill -- -$$` reads `kill this process and its subprocesses`, i.e. it will also send a `SIGTERM` to the script which again  `trap`s it, and again tries to kill this process, and again `trap`s it, and again ...

Whereas `pkill -P $$` sends the SIGTERM only to the subprocesses and thus will not lead to an infinite loop until we get a segfault.

I tested the patch. It works. Ready to merge!

**Comment by aaaaalbert** [comment]
Side note: The previous implementation has worked correctly for years. I wonder what might have changed in the shell's or `kill`'s behavior. (Come to think of it, maybe it's a `bash`/`dash` issue.)

**Pull request merged**
